### ISSUE TITLE
在安卓13上闪退

### ISSUE THREAD

**Issue by Aric-Sun** [fankes/TSBattery#30]
### 模块版本

4.2

### 作用域 APP

QQ

### 作用域 APP 版本

QQ 8.2.11(play)

### Android 版本

13

### Xposed 框架名称与版本号

LSPosed 1.8.6(6712) - Zygisk

### 系统是否已 Root

是

### 与当前作用域 APP 同作用域的 Xposed 模块

微X(正常)、QNotified(同闪退)、QQ瘦身(正常)

### 详细描述问题发生的具体原因

进入QQ设置页，模块部分显示为4.2(27)，点击模块，QQ闪退。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

----part 2 start----
[ 2023-02-06T15:17:06.812     1000:  1240:  1950 I/LSPosed-Bridge  ] [ INFO] 02-06 15:17:06 (ZygoteArgsHook) @startViaZygote force mount data: 10514 com.tencent.mobileqq
[ 2023-02-06T15:17:06.935    10514: 14449: 14449 I/LSPosed-Bridge  ] Loading module nil.nadph.qnotified from /data/app/~~hSpR8S8irv3Z1RL8TZBMRQ==/nil.nadph.qnotified-YQWIjX19baU3vb9OmnBJEQ==/base.apk
[ 2023-02-06T15:17:06.982    10514: 14449: 14449 I/LSPosed-Bridge  ]   Loading class nil.nadph.qnotified.startup.HookEntry
[ 2023-02-06T15:17:06.983    10514: 14449: 14449 I/LSPosed-Bridge  ] Loading module com.fankes.tsbattery from /data/app/~~nkMHL5B2YCZiaQuIbLBAqw==/com.fankes.tsbattery-HTmkpwdNRi0OO6pY2BeLtQ==/base.apk
[ 2023-02-06T15:17:06.995    10514: 14449: 14449 I/LSPosed-Bridge  ]   Loading class com.fankes.tsbattery.hook.HookEntry_YukiHookXposedInit
[ 2023-02-06T15:17:07.004    10514: 14449: 14449 I/LSPosed-Bridge  ] Loading module me.kyuubiran.qqcleaner from /data/app/~~6pJLeR0eVoIx97S-v1cv8Q==/me.kyuubiran.qqcleaner-z7Gk6BZQ_ZOI98FH18bw9A==/base.apk
[ 2023-02-06T15:17:07.010    10514: 14449: 14449 I/LSPosed-Bridge  ]   Loading class me.kyuubiran.qqcleaner.HookEntry
[ 2023-02-06T15:17:07.495    10514: 14449: 14449 I/LSPosed-Bridge  ] [TSBattery][I][com.tencent.mobileqq]--> All processes are completed for "com.tencent.mobileqq"
[ 2023-02-06T15:17:18.253    10514: 14449: 14449 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.mobileqq/com.fankes.tsbattery.ui.activity.parasitic.ConfigActivity}: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7868)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy6.getActivityInfo(Unknown Source)
	at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:558)
	at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:550)
	at d.e.n0(P:48)
	at d.e.L0(P:11)
	at d.e.I(P:17)
	at d.e.s(P:5)
	at d.b$b.a(P:22)
	at a.a.c(P:21)
	at androidx.activity.ComponentActivity.onCreate(P:8)
	at androidx.fragment.app.e.onCreate(P:1)
	at n4.a.onCreate(P:23)
	at q1.b.onCreate(P:1)
	at android.app.Activity.performCreate(Activity.java:8311)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at r80.callActivityOnCreate(Unknown Source:5)
	at p4.i.callActivityOnCreate(P:4)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	... 12 more
[ 2023-02-06T15:17:18.514     1000:  1240:  1950 I/LSPosed-Bridge  ] [ INFO] 02-06 15:17:18 (ZygoteArgsHook) @startViaZygote force mount data: 10514 com.tencent.mobileqq
[ 2023-02-06T15:17:18.663    10514: 16447: 16447 I/LSPosed-Bridge  ] Loading module nil.nadph.qnotified from /data/app/~~hSpR8S8irv3Z1RL8TZBMRQ==/nil.nadph.qnotified-YQWIjX19baU3vb9OmnBJEQ==/base.apk
[ 2023-02-06T15:17:18.734    10514: 16447: 16447 I/LSPosed-Bridge  ]   Loading class nil.nadph.qnotified.startup.HookEntry
[ 2023-02-06T15:17:18.735    10514: 16447: 16447 I/LSPosed-Bridge  ] Loading module com.fankes.tsbattery from /data/app/~~nkMHL5B2YCZiaQuIbLBAqw==/com.fankes.tsbattery-HTmkpwdNRi0OO6pY2BeLtQ==/base.apk
[ 2023-02-06T15:17:18.755    10514: 16447: 16447 I/LSPosed-Bridge  ]   Loading class com.fankes.tsbattery.hook.HookEntry_YukiHookXposedInit
[ 2023-02-06T15:17:18.772    10514: 16447: 16447 I/LSPosed-Bridge  ] Loading module me.kyuubiran.qqcleaner from /data/app/~~6pJLeR0eVoIx97S-v1cv8Q==/me.kyuubiran.qqcleaner-z7Gk6BZQ_ZOI98FH18bw9A==/base.apk
[ 2023-02-06T15:17:18.785    10514: 16447: 16447 I/LSPosed-Bridge  ]   Loading class me.kyuubiran.qqcleaner.HookEntry
[ 2023-02-06T15:17:19.380    10514: 16447: 16447 I/LSPosed-Bridge  ] [TSBattery][I][com.tencent.mobileqq]--> All processes are completed for "com.tencent.mobileqq"
[ 2023-02-06T15:17:19.448    10514: 16447: 16447 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.mobileqq/com.fankes.tsbattery.ui.activity.parasitic.ConfigActivity}: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7868)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy6.getActivityInfo(Unknown Source)
	at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:558)
	at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:550)
	at d.e.n0(P:48)
	at d.e.L0(P:11)
	at d.e.I(P:17)
	at d.e.s(P:5)
	at d.b$b.a(P:22)
	at a.a.c(P:21)
	at androidx.activity.ComponentActivity.onCreate(P:8)
	at androidx.fragment.app.e.onCreate(P:1)
	at n4.a.onCreate(P:23)
	at q1.b.onCreate(P:1)
	at android.app.Activity.performCreate(Activity.java:8311)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at r80.callActivityOnCreate(Unknown Source:5)
	at p4.i.callActivityOnCreate(P:4)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	... 12 more

</code></pre></details>

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by Aric-Sun** [comment]
QN更换为QA后正常

**Comment by fankes** [comment]
你是否来错地方了？

**Comment by Aric-Sun** [comment]
> 你是否来错地方了？

虽然结果看起来如此的滑稽，但是确实没有往互相影响的方向上想。非常抱歉打扰了您。
