### ISSUE TITLE
[问题与 BUG 反馈] 在应用转生中使用导致qq闪退

### ISSUE THREAD

**Issue by GuaiJieYo** [fankes/TSBattery#31]
### 模块版本

4.2

### 作用域 APP

QQ

### 作用域 APP 版本

8.9.25

### Android 版本

13

### Xposed 框架名称与版本号

应用转生 6.6.2

### 系统是否已 Root

否

### 与当前作用域 APP 同作用域的 Xposed 模块

QAuxiliary XAutoDaily QQ瘦身

### 详细描述问题发生的具体原因

点击qq中的TSBattery按钮就会闪退

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>
02-13 00:17:22.2 : QQ开始加载QAuxiliary模块
02-13 00:17:22.2 : QQ成功加载QAuxiliary模块
02-13 00:17:22.2 : QQ成功加载QAuxiliary模块
02-13 00:17:22.2 : QQ开始加载XAutoDaily模块
02-13 00:17:22.2 : QQ成功加载XAutoDaily模块
02-13 00:17:22.2 : QQ成功加载XAutoDaily模块
02-13 00:17:22.2 : QQ开始加载QQ瘦身模块
02-13 00:17:22.3 : QQ成功加载QQ瘦身模块
02-13 00:17:22.3 : QQ成功加载QQ瘦身模块
02-13 00:17:25.8 : QQ开始加载QAuxiliary模块
02-13 00:17:25.8 : QQ成功加载QAuxiliary模块
02-13 00:17:25.8 : QQ成功加载QAuxiliary模块
02-13 00:17:25.8 : QQ开始加载XAutoDaily模块
02-13 00:17:25.8 : QQ成功加载XAutoDaily模块
02-13 00:17:25.8 : QQ成功加载XAutoDaily模块
02-13 00:17:25.8 : QQ开始加载QQ瘦身模块
02-13 00:17:25.8 : QQ成功加载QQ瘦身模块
02-13 00:17:25.8 : QQ成功加载QQ瘦身模块
02-13 00:19:12.6 : QQ开始加载QAuxiliary模块
02-13 00:19:12.7 : QQ成功加载QAuxiliary模块
02-13 00:19:12.7 : QQ成功加载QAuxiliary模块
02-13 00:19:12.7 : QQ开始加载XAutoDaily模块
02-13 00:19:12.7 : QQ成功加载XAutoDaily模块
02-13 00:19:12.7 : QQ成功加载XAutoDaily模块
02-13 00:19:12.7 : QQ开始加载QQ瘦身模块
02-13 00:19:12.7 : QQ成功加载QQ瘦身模块
02-13 00:19:12.7 : QQ成功加载QQ瘦身模块
02-13 00:19:12.7 : QQ开始加载TSBattery模块
02-13 00:19:12.7 : QQ成功加载TSBattery模块
02-13 00:19:12.8 : QQ成功加载TSBattery模块
02-13 00:19:13.7 : [TSBattery][I][com.tencent.mobileqq]--> All processes are completed for "com.tencent.mobileqq"
02-13 00:19:15.8 : QQ开始加载QAuxiliary模块
02-13 00:19:15.8 : QQ成功加载QAuxiliary模块
02-13 00:19:15.8 : QQ成功加载QAuxiliary模块
02-13 00:19:15.8 : QQ开始加载XAutoDaily模块
02-13 00:19:15.8 : QQ成功加载XAutoDaily模块
02-13 00:19:15.8 : QQ成功加载XAutoDaily模块
02-13 00:19:15.8 : QQ开始加载QQ瘦身模块
02-13 00:19:15.8 : QQ成功加载QQ瘦身模块
02-13 00:19:15.8 : QQ成功加载QQ瘦身模块
02-13 00:19:15.8 : QQ开始加载TSBattery模块
02-13 00:19:15.8 : QQ成功加载TSBattery模块
02-13 00:19:15.9 : QQ成功加载TSBattery模块
02-13 00:19:16.6 : [TSBattery][I][com.tencent.mobileqq]--> All processes are completed for "com.tencent.mobileqq"
02-13 00:19:17.4 : [TSBattery][I][com.tencent.mobileqq]--> All processes are completed for "com.tencent.mobileqq:MSF"
02-13 00:19:20.9 : QQ报错
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.mobileqq/com.fankes.tsbattery.ui.activity.parasitic.ConfigActivity}: java.lang.reflect.InvocationTargetException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4631)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4842)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:113)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2928)
	at android.os.Handler.dispatchMessage(Handler.java:117)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.main(ActivityThread.java:9596)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at m3.c$b$a.a(P:49)
	at m3.c$b$a.d(P:6)
	at q1.b.onCreate(P:79)
	at android.app.Activity.performCreate(Activity.java:8488)
	at android.app.Activity.performCreate(Activity.java:8461)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1343)
	at mz.callActivityOnCreate(Unknown Source:5)
	at r80.callActivityOnCreate(Unknown Source:5)
	at io.github.qauxv.lifecycle.Parasitics$ProxyInstrumentation.callActivityOnCreate(Parasitics.java:5)
	at p4.i.callActivityOnCreate(P:4)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4602)
	... 12 more
Caused by: java.lang.LinkageError: Class androidx.appcompat.widget.d1 method void androidx.appcompat.widget.d1.setTextClassifier(android.view.textclassifier.TextClassifier) resolves differently in superclass android.widget.TextView: Parameter 0 type mismatch: java.lang.Class<android.view.textclassifier.TextClassifier,dalvik.system.PathClassLoader>(0x16ff49c0) vs java.lang.Class<android.view.textclassifier.TextClassifier,null>(0x71229330) (declaration of 'androidx.appcompat.widget.d1' appears in /data/app/~~Z3eebockwkBQPrP3uKuQlA==/com.fankes.tsbattery-8ecfPn6qPF-n0GxAfjzPgg==/base.apk)
	at com.google.android.material.theme.MaterialComponentsViewInflater.o(P:1)
	at d.j.r(P:299)
	at d.e.T(P:155)
	at d.e.onCreateView(P:1)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1075)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1011)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:975)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1137)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1098)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1140)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1098)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:696)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:540)
	at com.android.internal.policy.HwPhoneLayoutInflater.inflate(HwPhoneLayoutInflater.java:138)
	at l1.a.d(P:5)
	at l1.a.inflate(P:3)
	... 24 more

02-13 00:19:20.9 : QQ报错
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.mobileqq/com.fankes.tsbattery.ui.activity.parasitic.ConfigActivity}: java.lang.reflect.InvocationTargetException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4631)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4842)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:113)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2928)
	at android.os.Handler.dispatchMessage(Handler.java:117)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.main(ActivityThread.java:9596)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at m3.c$b$a.a(P:49)
	at m3.c$b$a.d(P:6)
	at q1.b.onCreate(P:79)
	at android.app.Activity.performCreate(Activity.java:8488)
	at android.app.Activity.performCreate(Activity.java:8461)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1343)
	at mz.callActivityOnCreate(Unknown Source:5)
	at r80.callActivityOnCreate(Unknown Source:5)
	at io.github.qauxv.lifecycle.Parasitics$ProxyInstrumentation.callActivityOnCreate(Parasitics.java:5)
	at p4.i.callActivityOnCreate(P:4)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4602)
	... 12 more
Caused by: java.lang.LinkageError: Class androidx.appcompat.widget.d1 method void androidx.appcompat.widget.d1.setTextClassifier(android.view.textclassifier.TextClassifier) resolves differently in superclass android.widget.TextView: Parameter 0 type mismatch: java.lang.Class<android.view.textclassifier.TextClassifier,dalvik.system.PathClassLoader>(0x16ff49c0) vs java.lang.Class<android.view.textclassifier.TextClassifier,null>(0x71229330) (declaration of 'androidx.appcompat.widget.d1' appears in /data/app/~~Z3eebockwkBQPrP3uKuQlA==/com.fankes.tsbattery-8ecfPn6qPF-n0GxAfjzPgg==/base.apk)
	at com.google.android.material.theme.MaterialComponentsViewInflater.o(P:1)
	at d.j.r(P:299)
	at d.e.T(P:155)
	at d.e.onCreateView(P:1)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1075)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1011)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:975)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1137)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1098)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1140)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1098)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:696)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:540)
	at com.android.internal.policy.HwPhoneLayoutInflater.inflate(HwPhoneLayoutInflater.java:138)
	at l1.a.d(P:5)
	at l1.a.inflate(P:3)
	... 24 more

02-13 00:19:29.3 : QQ报错
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.mobileqq/com.fankes.tsbattery.ui.activity.parasitic.ConfigActivity}: java.lang.reflect.InvocationTargetException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4631)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4842)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:113)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2928)
	at android.os.Handler.dispatchMessage(Handler.java:117)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.main(ActivityThread.java:9596)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at m3.c$b$a.a(P:49)
	at m3.c$b$a.d(P:6)
	at q1.b.onCreate(P:79)
	at android.app.Activity.performCreate(Activity.java:8488)
	at android.app.Activity.performCreate(Activity.java:8461)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1343)
	at mz.callActivityOnCreate(Unknown Source:5)
	at r80.callActivityOnCreate(Unknown Source:5)
	at io.github.qauxv.lifecycle.Parasitics$ProxyInstrumentation.callActivityOnCreate(Parasitics.java:5)
	at p4.i.callActivityOnCreate(P:4)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4602)
	... 12 more
Caused by: java.lang.LinkageError: Class androidx.appcompat.widget.d1 method void androidx.appcompat.widget.d1.setTextClassifier(android.view.textclassifier.TextClassifier) resolves differently in superclass android.widget.TextView: Parameter 0 type mismatch: java.lang.Class<android.view.textclassifier.TextClassifier,dalvik.system.PathClassLoader>(0x16ff49c0) vs java.lang.Class<android.view.textclassifier.TextClassifier,null>(0x71229330) (declaration of 'androidx.appcompat.widget.d1' appears in /data/app/~~Z3eebockwkBQPrP3uKuQlA==/com.fankes.tsbattery-8ecfPn6qPF-n0GxAfjzPgg==/base.apk)
	at com.google.android.material.theme.MaterialComponentsViewInflater.o(P:1)
	at d.j.r(P:299)
	at d.e.T(P:155)
	at d.e.onCreateView(P:1)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1075)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1011)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:975)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1137)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1098)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1140)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1098)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:696)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:540)
	at com.android.internal.policy.HwPhoneLayoutInflater.inflate(HwPhoneLayoutInflater.java:138)
	at l1.a.d(P:5)
	at l1.a.inflate(P:3)
	... 24 more

02-13 00:19:34.5 : QQ开始加载QAuxiliary模块
02-13 00:19:34.5 : QQ成功加载QAuxiliary模块
02-13 00:19:34.5 : QQ成功加载QAuxiliary模块
02-13 00:19:34.5 : QQ开始加载XAutoDaily模块
02-13 00:19:34.5 : QQ成功加载XAutoDaily模块
02-13 00:19:34.6 : QQ成功加载XAutoDaily模块
02-13 00:19:34.6 : QQ开始加载QQ瘦身模块
02-13 00:19:34.6 : QQ成功加载QQ瘦身模块
02-13 00:19:34.6 : QQ成功加载QQ瘦身模块
02-13 00:19:34.6 : QQ开始加载TSBattery模块
02-13 00:19:34.6 : QQ成功加载TSBattery模块
02-13 00:19:34.6 : QQ成功加载TSBattery模块
02-13 00:19:35.5 : [TSBattery][I][com.tencent.mobileqq]--> All processes are completed for "com.tencent.mobileqq"
02-13 00:19:35.8 : [TSBattery][I][com.tencent.mobileqq]--> All processes are completed for "com.tencent.mobileqq:MSF"
</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
这看起来并非此模块的问题，请移步 [QA](https://github.com/cinit/QAuxiliary)

**Comment by GuaiJieYo** [comment]
> 这看起来并非此模块的问题，请移步 [QA](https://github.com/cinit/QAuxiliary)

但是我禁用掉所有的模块 只开了tsbattery 点击按钮也会闪退

**Comment by fankes** [comment]
请更换其它免 Root 框架解决，例如太极或 [LSPatch](https://github.com/LSPosed/LSPatch)

**Comment by EmptyDreams** [comment]
> 请更换其它免 Root 框架解决，例如太极或 [LSPatch](https://github.com/LSPosed/LSPatch)

在我尝试从 qq 中进入 TSBattery 设置时会出现崩溃，但是我可以从 TSBattery 中打开 qq 并进入设置，并且此时我又可以从 qq 中进入 tsb 的设置了，但是关闭 qq 后又回到初始状态。

请问这种情况下 tsb 的功能能否正常工作？

**Comment by fankes** [comment]
界面只是一个显示意义上的功能，只要你能看到界面就是正常工作的

**Comment by EmptyDreams** [comment]
> 界面只是一个显示意义上的功能，只要你能看到界面就是正常工作的

试了一下不行，用着用着 qq 就打不开了，启动 qq 一直白屏。

**Comment by fankes** [comment]
> > 界面只是一个显示意义上的功能，只要你能看到界面就是正常工作的
> 
> 试了一下不行，用着用着 qq 就打不开了，启动 qq 一直白屏。

那就只能 [这样](https://github.com/fankes/TSBattery/issues/31#issuecomment-1427316577) 了
